<?php
//include("/var/www/qlync_admin/header.php");
//include("/var/www/qlync_admin/menu.php");
############### Authentication Section
if (!isset($_SESSION["Email"]) ) exit(); 
/*
$sql="select * from qlync.menu where Name = 'Login Log'";
sql($sql,$result,$num,0);
fetch($db,$result,0,0);
$sql="select * from qlync.right_tree where Cfun='{$db["ID"]}' and `Right` = 1";
sql($sql,$result,$num,0);
$right=0;
$oem_id="";
for($i=0;$i<$num;$i++)
{
        fetch($db,$result,$i,0);
        if($_SESSION["{$db["Fright"]}_qlync"] ==1)
        {
                $right+=1;
                if($db["Oem"] == "0")
                {
                        $oem_id="N99";
                }
                if($db["Oem"] == "1" and $oem_id == "")
                {
                        $oem_id=$_SESSION["CID"];
                }
        }
}
if($right  == "0")
        exit();
*/
############  Authentication Section End
?>