<?php
/****************
 *Validated on Jun-8,2017,
 * list recording_list end date
 * Export to excel and download from     
 *Writer: JinHo, Chang
*****************/
include("../../header.php");
include("../../menu.php");
//for $RPICAPP_USER_PWD
if (file_exists("_iveda.inc"))
  require_once ("_iveda.inc");
else die("missing camera variable include file.");
if  ($_REQUEST['key']!=$RPICAPP_USER_PWD[$oem][0])
	if (!isset($_SESSION["Email"]) ) exit();

ini_set('memory_limit','128M'); //if server >20, memory will be over 64M
require_once '../billing/Classes/PHPExcel.php';
require_once '../billing/Classes/PHPExcel/IOFactory.php';
include  '../billing/Classes/PHPExcel/Writer/Excel2007.php';  //xlsx
define("EXCEL_EXT",".xlsx");
//form billing log folder
define("DL_REPORT_FOLDER","/var/www/qlync_admin/plugin/billing/log/");
define("WDL_REPORT_FOLDER","/plugin/billing/log/");
$debugCamera = [
"T04" => array("MT0456175187",
"MT0456173175",
"MT0456173174",
"MT0456173173",
"MT0456173172",
"MT0456173171",
"MT0456173170",
"MT0456173079",
"MT0456173078",
"MT0456173077",
"MT0456173076"),
"T05" => array(
"001BFE06CBB3",
"MT0569126555",
"MT0569126554",
"MT0569126553",
"MT0569126552",
"MT0569126551",
"MT0569126550",
"MT0569126459",
"MT0569126458",
"MT0569126457",
"MT0569126456"),
"K01" => array(
"MK0179082236",
"MK0179082235",
"MK0179082234",
"MK0179082233",
"MK0179082232",
"MK0179082231",
"MK0179082230",
"MK0179082139",
"MK0179082138",
"MK0179082137",
"001BFE06AC2B",
"001BFE06CDAC")  
];
$siteAdminName = [
'T04'=>'台北市道路管線中心',
'T05'=>'桃園市道路挖掘服務中心',
'K01'=>'高雄市道路挖掘管理中心',
'T06'=>'即時工務影像管理服務', 
'X02'=>'MegasysXpress'
];
//var_dump($_REQUEST);

function getlastExcel()
{
	global $oem;
    $files = scandir(DL_REPORT_FOLDER, 1);
    for($i=0;$i<sizeof($files);$i++){
        if ($files[$i]=="..") continue;
        else if ($files[$i]==".") continue;
        else if (strpos($files[$i], EXCEL_EXT) !== FALSE)
        	if (preg_match("/^[A-Z]{1}[0-9]{2}_[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])_[0-9]{6}/",$files[$i])) //T04_2017-08-09_135858.xlsx
            return $files[$i];
        else continue; 
    } 
    return "";
} 

function createExcel($deviceArray,$unbindArray)
{
//var_dump($unbindArray);
    error_reporting(E_ALL);
    global $oem,$siteAdminName;
    $CurrentDate = new DateTime();

    $REPORT_DATE=$CurrentDate->format('Y-m-d_His'); 
    $SITE_SERVER = $oem;
    $filename = "{$oem}_" . $REPORT_DATE .EXCEL_EXT;     
    $filepath = DL_REPORT_FOLDER. $filename; 
//echo $filepath;
    $objPHPExcel = new PHPExcel();
//echo date('H:i:s') . " Set properties\n";
    $objPHPExcel->getProperties()->setCreator($oem);
    $objPHPExcel->getProperties()->setTitle("{$oem} Device Status");
    $objPHPExcel->getProperties()->setSubject("{$oem} Device Status");
    $objPHPExcel->getProperties()->setDescription("{$oem} Device Status, generated by PHP.");
//echo date('H:i:s') . " Add some data\n";
    $objPHPExcel->setActiveSheetIndex(0);
    $objPHPExcel->getActiveSheet()->setTitle("Report {$oem}-{$REPORT_DATE}");
    $objPHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(15);
    $objPHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(30);
    $objPHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(30);
    $objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(30);
    $objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(30);

    //$objPHPExcel->getDefaultStyle()->getAlignment()->setVertical(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $listsize=sizeof($deviceArray);
    $excelIndex = 6;
    $setlistColumn=$listsize + $excelIndex;
    $objPHPExcel->getActiveSheet()->getStyle("A1:A{$setlistColumn}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle("B1:B{$setlistColumn}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->getStyle("C1:C{$setlistColumn}")->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
    $objPHPExcel->getActiveSheet()->SetCellValue('B4', $listsize);
    $objPHPExcel->getActiveSheet()->SetCellValue('G4', sizeof($unbindArray));
    $objPHPExcel->getActiveSheet()->SetCellValue('B2', $siteAdminName[$oem]);
    #$objPHPExcel->getActiveSheet()->SetCellValue('B2', $SITE_SERVER);
    #$objPHPExcel->getActiveSheet()->SetCellValue('C2', "Server# ".count($uid_list));
    $objPHPExcel->getActiveSheet()->SetCellValue('C2', $CurrentDate->format('Y-m-d H:i:s'));
    #$objPHPExcel->getActiveSheet()->SetCellValue('B3', $REPORT_DATE);
    #$objPHPExcel->getActiveSheet()->SetCellValue('C3', $SEL_LOG_FILE);

    $objPHPExcel->getActiveSheet()->SetCellValue('A5', '帳號');
    $objPHPExcel->getActiveSheet()->getStyle('A5')->applyFromArray(array('fill' => array('type' => PHPExcel_Style_Fill::FILL_SOLID,'color' => array('rgb' => 'c0c0c0'))));
    $objPHPExcel->getActiveSheet()->SetCellValue('B5', '攝影機MAC');
    $objPHPExcel->getActiveSheet()->getStyle('B5')->applyFromArray(array('fill' => array('type' => PHPExcel_Style_Fill::FILL_SOLID,'color' => array('rgb' => 'c0c0c0'))));
    $objPHPExcel->getActiveSheet()->SetCellValue('C5', '最後錄影紀錄');
    $objPHPExcel->getActiveSheet()->getStyle('C5')->applyFromArray(array('fill' => array('type' => PHPExcel_Style_Fill::FILL_SOLID,'color' => array('rgb' => 'c0c0c0'))));
    $objPHPExcel->getActiveSheet()->SetCellValue('D5', '最後連上紀錄');
    $objPHPExcel->getActiveSheet()->getStyle('D5')->applyFromArray(array('fill' => array('type' => PHPExcel_Style_Fill::FILL_SOLID,'color' => array('rgb' => 'c0c0c0'))));
    $objPHPExcel->getActiveSheet()->SetCellValue('G5', '無綁定攝影機');
    $objPHPExcel->getActiveSheet()->getStyle('G5')->applyFromArray(array('fill' => array('type' => PHPExcel_Style_Fill::FILL_SOLID,'color' => array('rgb' => 'c0c0c0'))));


     foreach($deviceArray as $data){
     		$objPHPExcel->getActiveSheet()->setCellValueExplicit("A{$excelIndex}", strval($data['owner_name']),PHPExcel_Cell_DataType::TYPE_STRING); 
     		$objPHPExcel->getActiveSheet()->setCellValueExplicit("B{$excelIndex}", strval($data['mac_addr']),PHPExcel_Cell_DataType::TYPE_STRING);
        //$objPHPExcel->getActiveSheet()->SetCellValue("A{$excelIndex}", strval($data['owner_name']));
        //$objPHPExcel->getActiveSheet()->SetCellValue("B{$excelIndex}", strval($data['mac_addr']));
        $objPHPExcel->getActiveSheet()->SetCellValue("C{$excelIndex}", $data['video_enddate']);
        $objPHPExcel->getActiveSheet()->SetCellValue("D{$excelIndex}", $data['update_date']);
        $excelIndex++;
     }
    $excelIndex = 6;
    foreach($unbindArray as $data){
    	$objPHPExcel->getActiveSheet()->setCellValueExplicit("G{$excelIndex}", strval($data),PHPExcel_Cell_DataType::TYPE_STRING);
			//$objPHPExcel->getActiveSheet()->SetCellValue("G{$excelIndex}", strval($data));
			$excelIndex++;
		}

    $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
    $objWriter->save($filepath);
//echo date('H:i:s') . " Done writing file.\r\n";
    return $filename;              
}
function execSQL($sql)
{
    sql($sql,$result,$num,0);
    if ($result) return true;
    return false;  
}

//alread create in debug/_iveda.inc
//function StringToDateTime($string)

function getLastVideoArray(&$enddate)
{
	//$sql="select device_uid, end from isat.recording_list group by device_uid order by end asc;";
	$sql="select device_uid, end FROM (SELECT * FROM  isat.recording_list order by end desc) AS mydate group by device_uid order by end asc;";
	sql($sql,$result,$num,0);
	for($i=0;$i<$num;$i++){
		fetch($arr,$result,$i,0);
		$enddate[$arr['device_uid']] = $arr['end'];
	}
}

function isDebugSample($mac)
{
	global $debugCamera,$oem;
	foreach ($debugCamera[$oem] as $debugmac)
	{
			if ($debugmac == $mac)
				return true;
	}
	return false; 
}

function createNoBindDeviceTable($whereParam="")
{ //and mac not like 'MT04%' //limit
	//where need to start with and
  if ($whereParam=="")
    $sql = "select mac from isat.series_number where uid is NULL;";
  else $sql = "select mac from isat.series_number where uid is NULL {$whereParam}";
  //echo $sql;
    sql($sql,$result,$num,0);
  $html = "<b>Not Bind Device:</b> Query Total {$num}";

  $html .= "\n<table id='tbl4' class=table_main><tr class=topic_main><td>#</td><td>攝影機MAC</td></tr>";
  $serviceb = array();
  for($i=0;$i<$num;$i++){
    fetch($arr,$result,$i,0);
    #$html.="<tr class=tr_2><td>{$arr['id']}</td><td>{$arr['mac']}</td></tr>";
    $html.="<tr class=tr_2><td>".strval($i+1)."</td><td>{$arr['mac']}</td></tr>";
    if (!isDebugSample($arr['mac']))
    	$serviceb[$i]=$arr['mac'];
  }
  $html.="</table>";
  
  if ($_REQUEST['uid_filter'] =="(EXCEL)")
  	return $serviceb;
  else return $html;
}
function createDeviceTable($whereParam="",$limitParam="")
{
 	//$sql = "select c1.mac_addr, c1.name as camera_name, c1.user_name as owner_name, c2.update_date from isat.query_info as c1 left join isat.device as c2 on c1.uid = c2.uid {$whereParam} group by c1.mac_addr {$limitParam}";
   $sql = "select c1.id,  c1.uid,c1.mac_addr, c1.name as camera_name, c1.owner_id, c2.name as owner_name, c1.update_date from isat.device as c1 left join isat.user as c2 on c1.owner_id = c2.id {$whereParam} group by c1.mac_addr {$limitParam} order by owner_name";
  //echo $sql;
    sql($sql,$result,$num,0);
    $services = array();
    getLastVideoArray($serviceDateArr);

 
    for($i=0;$i<$num;$i++){
      fetch($arr,$result,$i,0);
      $arr['owner_id_name'] = $arr['owner_id'] . " : ". $arr['owner_name'];
		  $utcdate= new DateTime(date ("Y-m-d H:i:s", $arr['update_date']), new DateTimeZone('UTC'));
		  //$utcdate->setTimezone( new DateTimeZone($time_zone) ); 
      $arr['update_date'] = $utcdate->format("Y-m-d H:i:s");
      if ($serviceDateArr[$arr['uid']]!="")
        $arr['video_enddate']= StringToDateTime($serviceDateArr[$arr['uid']]);//$serviceDateArr[$arr['uid']];
      if (!isDebugSample($arr['mac_addr']))
      		$services[$i] = $arr;
    }//for
  if (strpos($whereParam, "c1.mac_addr") !== FALSE) // === FALSE not found
		$whereParam=str_replace("c1.mac_addr","mac_addr",$whereParam);
  $sql = "select mac_addr as total from isat.device {$whereParam} group by mac_addr";//exclude virtual mac
  sql($sql,$result_total,$num_total,0);
  $html = "<b>Recording Device:</b> Query Total {$num_total}";

  #$html .= "\n<table id='tbl4' class=table_main><tr class=topic_main><td>ID</td><td>MAC</td><td>Last Video End Date</td>"; //add table header 3
  $html .= "\n<table id='tbl4' class=table_main><tr class=topic_main><td>帳號</td><td>攝影機MAC</td><td>最後錄影紀錄</td>";
	$html .= "<td>最後連上紀錄</td>";
	$html .= "</tr>";
  foreach($services as $service)
  {
		$html.= "\n<tr class=tr_2>\n";
    #$html.= "<td>{$service['id']}</td>\n";
    $html.= "<td>{$service['owner_name']}</td>\n";
    $html.= "<td>{$service['mac_addr']}</td>\n"; // / {$service['camera_name']}
    $html.= "<td>{$service['video_enddate']}</td>\n";
    $html.= "<td>{$service['update_date']}</td>\n";

    $html.= "</tr>\n";
	}
  $html .= "</table>\n";   //add table end
  if ($_REQUEST['uid_filter'] =="(EXCEL)")
  	return $services;
  else return $html;
}


function selectDeviceUid($tagName)
{
    $sql = "select DISTINCT c1.uid,c1.owner_id,c2.name as owner_name from isat.device as c1 left join isat.user as c2 on c1.owner_id = c2.id order by c1.uid";
    sql($sql,$result,$num,0);
    $html = "<select name='{$tagName}'>";
    for($i=0;$i<$num;$i++){
      fetch($arr,$result,$i,0);
      $arr['owner_id_name'] = $arr['owner_id']. " : " .$arr['owner_name'];
      $html.= "\n<option value='{$arr['uid']}_{$arr['owner_id']}'>{$arr['uid']} ({$arr['owner_id_name']})</option>";
    }//for

  $html .= "</select>\n";   //add table end
	echo $html;
}
function selectUserList($tagName)
{
   $sql = "select id, name from isat.user order by id";
   sql($sql,$result,$num,0);

  $html = "<select name='{$tagName}'>";
    for($i=0;$i<$num;$i++){
      fetch($arr,$result,$i,0);
      $arr['id_name'] = $arr['id']. " : " .$arr['name'];
      $html.= "\n<option value='{$arr['id']}'>{$arr['id_name']}</option>";
    }//for
  $html .= "</select>\n";   //add table end
	echo $html;
}
if ($_REQUEST['uid_filter'] =="(EXCEL)")
	$filename=createExcel(createDeviceTable(),createNoBindDeviceTable());
?>
<!--html>
<head>
</head>
<body-->
<script>
function optionValue(thisformobj, selectobj)
{
	var chosenoption=selectobj.options[selectobj.selectedIndex];
  thisformobj.value = chosenoption.value;
}
</script>
<div align=center><b><font size=5>設備使用狀態</font></b></div>
<form method=post action="<?php echo $_SERVER['PHP_SELF'];?>">

<select name="uid_filter" id="uid_filter" onchange="optionValue(this.form.uid_filter, this);this.form.submit();">
<option value="(FOLD)" <?php if($_REQUEST['uid_filter'] =="(FOLD)" ) echo "selected";?>>不顯示</option>
<option value="(No IvedaMobile)" <?php if($_REQUEST['uid_filter'] =="(No IvedaMobile)" ) echo "selected";?>>顯示攝影機</option>
<option value="(ALL)" <?php if($_REQUEST['uid_filter'] =="(ALL)" ) echo "selected";?>>顯示全部設備</option>
<option value="(EXCEL)" <?php if($_REQUEST['uid_filter'] =="(EXCEL)" ) echo "selected";?>>EXCEL報表</option>
</select>
&nbsp;
<?php
if (isset($_REQUEST['key']))
	echo "<input type=hidden name=key id=key value='{$_REQUEST['key']}'>";
if (($_REQUEST['uid_filter'] !="(EXCEL)")){
$filepath = getlastExcel();
if ($filepath !="")
	if (file_exists(DL_REPORT_FOLDER.$filepath))
		echo "<a href='https://".$_SERVER['SERVER_NAME'].":8080".WDL_REPORT_FOLDER."{$filepath}' download>Download {$filepath}</a>";
}
?>
</form>
<?php
if ($_REQUEST['uid_filter'] =="(ALL)" ){
     echo createDeviceTable("","");
     echo createNoBindDeviceTable("");
}else if (($_REQUEST['uid_filter'] =="(No IvedaMobile)")  ){
		 echo createDeviceTable("where c1.mac_addr NOT LIKE 'M{$oem}%'","");
		 echo  createNoBindDeviceTable(" and mac NOT LIKE 'M{$oem}%'");
}else if (($_REQUEST['uid_filter'] =="(EXCEL)")){
	if ((isset($filename)) and (file_exists(DL_REPORT_FOLDER. $filename))){
 	echo "<a href='https://".$_SERVER['SERVER_NAME'].":8080".WDL_REPORT_FOLDER."{$filename}' download>Download {$filename}</a>";
		}		      
}
?>
<br>
	</div>
</body>
</html>